version: 2.1
jobs:
  build:
    docker:
      - image: cimg/go:1.17
        auth:
          username: vijenderpanda12
          password: Vijender@1124  # context / project UI env-var reference
    steps:
      - checkout
      # ... steps for building/testing app ...

      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true

      # build and push Docker image
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t vijenderpanda12/react_client_app:$TAG .
          echo Vijender@1124 | docker login -u vijenderpanda12 --password Vijender@1124
          docker push vijenderpanda12/react_client_app:$TAG
